Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 3
  end

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", ip: "192.168.149.2"
  config.vm.provision "shell", inline: "sudo apt-get install -y python"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.galaxy_role_file = "requirements.yml"
  end
end
