---
- name: Write netbox nginx configuration
  template:
    src: templates/netbox-nginx.conf.j2
    dest: /etc/nginx/sites-available/netbox.conf
  notify: restart nginx

- name: Enable netbox in nginx
  file:
    src: /etc/nginx/sites-available/netbox.conf
    dest: /etc/nginx/sites-enabled/netbox.conf
    state: link
  notify: restart nginx

- name: Remove nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
