---
- name: Read existing secret key
  shell: >
    cat {{ netbox_install_dir }}/netbox/netbox/configuration.py
    | sed -n "s/^SECRET_KEY *= *'\(.*\)'/\1/p"
  register: __existing_key
  failed_when: false
  ignore_errors: true
  changed_when: false

- name: Check if secret key must be generated
  set_fact:
    _need_key: "{{ __existing_key.rc != 0 or __existing_key.stdout|length == 0 }}"

- name: Use existing secret key
  set_fact:
    netbox_secret_key: "{{ __existing_key.stdout }}"
  when: not _need_key

- name: Generate secret key
  set_fact:
    netbox_secret_key: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
  when: _need_key
